# Generated by Django 4.2 on 2024-05-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chofer',
            old_name='patente_vehiculo',
            new_name='vehiculo',
        ),
        migrations.RenameField(
            model_name='registrocontabilidad',
            old_name='patente_vehiculo',
            new_name='vehiculo',
        ),
    ]
