# Generated by Django 4.2 on 2024-05-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_patente_vehiculo_chofer_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chofer', to='app.vehiculo'),
        ),
    ]
